### ISSUE TITLE
Connecting to multiple Phoenix Channels on same Websocket

### ISSUE THREAD

**Issue by mukulashokjoshi** [fbonetti/elm-phoenix-socket#14]
@fbonetti 

Thanks for this useful library for enabling Elm connectivity/interface to Phoenix Channels.

This may not be an issue as such, but can you confirm if it is possible to connect to multiple Phoenix Channels on the same Websocket using the Elm Phoenix Socket library?

Or is it cleaner to create multiple socket and socket routes/handlers in the Phoenix Application?

Any directions or do's/don'ts would be useful

Thanks

**Comment by fbonetti** [comment]
Yes, Phoenix Channels were designed to use a single connection to the server, since you can only have one `WebSocket` connection to a specific port on a host. You can open as many channels as you want.

**Comment by fbonetti** [comment]
From the docs:

> Phoenix holds a single connection to the server and multiplexes your channel sockets over that one connection. 

http://www.phoenixframework.org/docs/channels

**Comment by mukulashokjoshi** [comment]
Thanks for the confirmation

**Comment by OvermindDL1** [comment]
On a related note, any way for both Elm and Javascript to have the websocket open?  We have older code that would be nice to work with elm code for phoenix.

**Comment by fbonetti** [comment]
@OvermindDL1 I believe you can only have one WebSocket connection for a given host + port, but I'm not sure if that's true. Why don't you give it a try?

**Comment by OvermindDL1** [comment]
That is the case, hence why I need the javascript and elm sides to share the connection somehow?
