### ISSUE TITLE
How is the best way to process a reply?

### ISSUE THREAD

**Issue by AdrianRibao** [fbonetti/elm-phoenix-socket#15]
After pushing data, phoenix replies with the updated content from the db, and some extra information. I need to handle that reply, but I'm not sure how to do it after reading the code and the example.

Is this done with onOk? (http://package.elm-lang.org/packages/fbonetti/elm-phoenix-socket/2.0.0/Phoenix-Push#onOk)

Thank you!

**Comment by fbonetti** [comment]
If you backend code looks like this, that should work:

https://github.com/chrismccord/phoenix_chat_example/blob/master/web/channels/room_channel.ex#L42-L45

**Comment by AdrianRibao** [comment]
thank you!

I've been playing for a few hours with this library trying to call JoinChannel on init instead of using the button, Is that possible?

I know this is unrelated but I'm a newbie with elm and it seems pretty hard sometimes.

Thank you!

**Comment by AdrianRibao** [comment]
Well, in the elm-discuss mailing list already solved this problem, it is like this:

`init = update JoinChannel initModel`

Thank you again!
