### ISSUE TITLE
Detect server disconnect

### ISSUE THREAD

**Issue by jxxcarlson** [fbonetti/elm-phoenix-socket#29]
I am using elm-phoenix-socket to indicate to the user whether he has a live connection to the phoenix backend.  This is working very well in one direction but not so well in another. The Elm client pings the server and if it gets a successful response, it displays "Online" to the user, "Offline" in the case of failure.  

The transition from "Offline" on "Online" is instantaneous from the perspective of the user.  In the other direction, there is a delay of about 5 seconds because I change state if the Heartbeat event is detected.  What instead I need to detect is the event below which I've gotten from the Javascript console.  

Is there a way to do this with elm-phoenix-socket?

Thanks!

```
app.js:18881 WebSocket connection to 'ws://localhost:4000/socket/websocket' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
```

**Comment by maxstr** [comment]
Unfortunately it is not possible to accomplish this with "native" Elm. The hope is that .19 will provide a better WebSocket API, allowing for detection of closed sockets, however this does not currently exist. If you are willing to install an effect manager, I'd recommend https://github.com/saschatimme/elm-phoenix. https://saschatimme.github.io/elm-phoenix/channel.html#onDisconnect.
