### ISSUE TITLE
Elm 0.19 Update

### ISSUE THREAD

**Issue by optikfluffel** [fbonetti/elm-phoenix-socket#32]
Elm `0.19` [is released](https://github.com/elm/compiler/releases/tag/0.19.0)! 🎉

But before updating, we'll have to wait for a new [elm-lang/websocket](https://github.com/elm-lang/websocket) release, I guess.

**Comment by DevotionGeo** [comment]
When is it going to be updated for Elm 0.19?

**Comment by optikfluffel** [comment]
@DevotionGeo we still have to wait for a new websocket package. Evan wrote about it over [at discourse.elm-lang.org](https://discourse.elm-lang.org/t/updating-packages/1771). Or you could use [slashmili/phoenix-socket](https://github.com/slashmili/phoenix-socket), with long polling, as a workaround for now.

**Comment by DevotionGeo** [comment]
I'll use slashmili/phoenix-socket in my current project, and will delay another project for elm-phoenix-socket to update.

Thank you for creating and maintaining this nice package!

**Comment by synalysis** [comment]
> @DevotionGeo we still have to wait for a new websocket package. Evan wrote about it over [at discourse.elm-lang.org](https://discourse.elm-lang.org/t/updating-packages/1771). Or you could use [slashmili/phoenix-socket](https://github.com/slashmili/phoenix-socket), with long polling, as a workaround for now.

@optikfluffel It seems that [slashmili/phoenix-socket](https://github.com/slashmili/phoenix-socket) doesn't allow to receive messages from Phoenix so the only option I see currently is to use the Phoenix Channels JS file and ports. Or have I overlooked something?

**Comment by optikfluffel** [comment]
@synalysis you mean handling incoming messages from a Channel? That would be possible, have a look at [Example.elm](https://github.com/slashmili/phoenix-socket/blob/master/example/src/Example.elm#L80).

**Comment by synalysis** [comment]
@optikfluffel 1000 thanks! You saved me quite some work :-) Apparently I was misled by looking also into this example: [fbonetti/elm-phoenix-socket/examples/Chat.elm](https://github.com/fbonetti/elm-phoenix-socket/blob/master/examples/Chat.elm#L66) - there the receiving of messages is connected to the socket, not channel. So this solution is good enough for now.

**Comment by jonator** [comment]
Is there any update on the state of this? I see websocket has been updated for 19.

Thanks!

**Comment by optikfluffel** [comment]
@jonator still seems a little too early in my opinion, it's only `alpha-1.0.3` and also not yet released on [package.elm-lang.org](https://package.elm-lang.org)

**Comment by optikfluffel** [comment]
@jonator Where did you find an update? Last commit I see at [elm-lang/websocket](https://github.com/elm-lang/websocket) is from May 27 2018 and I also don't find anything at [github.com/elm](https://github.com/elm).

**Comment by jonator** [comment]
@optikfluffel Apologies, should have been more descriptive.
https://package.elm-lang.org/packages/billstclair/elm-websocket-client/latest/
I found this to be the current websocket solution for .19, despite this project not using it.

**Comment by optikfluffel** [comment]
@jonator It looks like you have to use Ports for this websocket client anyway, so you could also use Phoenix' regular js stuff and get it to speak to Elm the same way.
On that note: I don't really think it would be a good idea to change this package here to use ports.

**Comment by jonator** [comment]
@optikfluffel I agree ports would not be suitable in this package. That client's readme mentioned an eventual redesign of elm/websocket for elm 19. We need to wait for that to be released before updating this package. As for my project, I'm going to use ports to interface with the js phoenix library.

**Comment by chazsconi** [comment]
I have created a Elm 0.19 library using ports to communicate with Phoenix.  Although this is based on the API from https://github.com/saschatimme/elm-phoenix you may find it useful.

Please see: 
https://github.com/chazsconi/elm-phoenix-ports
