### ISSUE TITLE
Client stops receiving messages 60 seconds after load

### ISSUE THREAD

**Issue by hojgr** [fbonetti/elm-phoenix-socket#5]
Hello,

awesome package! After a little fiddling around I got it to work but encountered something weird. My backend is broadcasting message every 200 ms. Those are 3 messages that alternate (1,2,3,1,2,3,...)

But 60 seconds after loading the page the messages stop coming. Server is still sending them (on refresh it works again) but nothing happens on client. No `onClose` message comes to update, no error (I think) happens. 

What could be the problem? Has it happend to anyone else?

Thanks!

**Comment by hojgr** [comment]
Yes, I do have it on. Messages just stop being printed too.

**Comment by hojgr** [comment]
I fixed it. Phoenix's `Phoenix.Transports.WebSocket` has a `:timeout` option that is set to 60 second by default. I've set it to `:infinity` and it works like a charm.

**Comment by fbonetti** [comment]
@hojgr This may be related to https://github.com/fbonetti/elm-phoenix-socket/issues/7

**Comment by OvermindDL1** [comment]
Yeah setting this to :infinity is very very bad and can cause old connections that should be dropped to remain open until the 30minute TCP timeout.  @hojgr you should not set that to infinity and until this library fixes the heartbeat then you should perform your own heartbeat (send anything once every twenty-thirty seconds or so).  This is what the heartbeat is for and makes it plainly obvious that the heartbeat is not implemented yet.
