### ISSUE TITLE
Add support for Phoenix.Presence (almost ready for a PR)

### ISSUE THREAD

**Issue by knewter** [fbonetti/elm-phoenix-socket#8]
I've added support for Phoenix.Presence, here: https://github.com/knewter/elm-phoenix-socket/tree/feature/nested_records

I haven't written up any docs yet but the example `Phoenix.elm` works as expected.  You can run it against https://github.com/knewter/presence_chat

Thoughts on this?  Would love API suggestions or some clue re: whether or not you're interested in merging the feature.  If not, I can always push a separate package that integrates with `elm-phoenix-socket` but I think it should be in here.

Also, I know @chrismccord has expressed interest in getting an official Phoenix elm client out, if I could facilitate a conversation around that :)

This is, obviously, a packate that I want to see move forward badly :)

**Comment by knewter** [comment]
Also, Phoenix 1.2 just came out so it's officially part of the API now :)

**Comment by fbonetti** [comment]
I'm definitely interested in merging this feature, but I'm going to be out of town this weekend. I'll take a look early next week.

**Comment by knewter** [comment]
\o/ just wanted to know you were still around. Thanks!

On Jun 24, 2016 1:59 PM, "Frank Bonetti" <notifications@github.com> wrote:

I'm definitely interested in merging this feature, but I'm going to be out
of town this weekend. I'll take a look early next week.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/fbonetti/elm-phoenix-socket/issues/8#issuecomment-228432241>,
or mute the thread
<https://github.com/notifications/unsubscribe/AAAO9az5Rh_gsZDno7Whje-NK1gImnSZks5qPCkUgaJpZM4I84Ui>
.

**Comment by fbonetti** [comment]
I looked over your code and it looks good to me. I wish I could give you more constructive feedback but I've actually never used Presence or looked at the code for it. I'll have to play around with it at some point.

**Comment by knewter** [comment]
So would a good next course of action be to update the readme and add some docs to the package?  Trying to determine what would remains to make it mergeable

**Comment by jeffcole** [comment]
@knewter thanks for this work! I'm looking forward to this making it into a package 😃 

Just curious: why is your preference to merge into `elm-phoenix-socket`? It doesn't look like `Presence.elm` depends upon it.

**Comment by knewter** [comment]
@jeffcole I could publish separately, and suppose I perhaps should.  My reasoning is that the official phoenix channels js library has presence support directly in it, and this way this package could be analogous to the official library.  Also, @chrismccord is looking for an official phoenix elm package, and I think this is a good candidate - I'd love to make that happen if @fbonetti and @chrismccord were both inclined.

**Comment by jeffcole** [comment]
@knewter that makes sense.

Since there might be folks that just want sockets without presence (seeing as these are client side libraries and some might be concerned about size), what do you think about an `elm-phoenix-presence` and then an `elm-phoenix` that simply bundles `elm-phoenix-socket` and `elm-phoenix-presence`?

At the least then folks could start playing with presence without the need to wait for an official Phoenix package 🚀

**Comment by knewter** [comment]
@jeffcole I think this is something I should do.  I'd also say, though, that the closure compiler should be able to strip out the bits that are unused.
